project:
  type: website
  output-dir: docs

format:
  html:
    css: styles/styles.css
    theme: 
      light: styles/light-theme.scss
      dark: styles/dark-theme.scss
    toc: true
    bibliography: "references.bib"

website:
  title: "Thomas Winninger"
  favicon: "assets/favicon.png"
  site-url: "https://sckathach.github.io"
  repo-url: "https://github.com/Sckathach/Sckathach.github.io"
  issue-url: "https://github.com/Sckathach/Sckathach.github.io/issues"
  repo-actions: [edit, source, issue]
  twitter-card: true
  reader-mode: true
  open-graph:
    description: "My (Thomas Winninger) personal website."
  page-footer:
    right:
      - text: "Home"
        href: "https://sckathach.github.io"
      - text: "About"
        href: "about.qmd"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/sckathach"
    left:
      - text: "SSR"
        href: "blogs/subspace-rerouting/index.qmd"
    right: 
      - text: "About"
        href: "about.qmd"
      - text: "Research"
        href: "research.qmd"
      - text: "Writing"
        href: "index.qmd"
  search:
    show-item-context: true
    type: overlay