project:
  type: website
  output-dir: docs

format:
  html:
    css: styles.css
    theme: 
      light: light-theme.scss
      dark: dark-theme.scss
    toc: true
    bibliography: "references.bib"

website:
  title: "Sckathach's posts"
  favicon: "assets/favicon.png"
  site-url: "https://sckathach.github.io"
  repo-url: "https://github.com/Sckathach/Sckathach.github.io"
  issue-url: "https://github.com/Sckathach/Sckathach.github.io/issues"
  repo-actions: [edit, source, issue]
  twitter-card: true
  reader-mode: true
  open-graph:
    description: "The very super website of the super Sckathach!"
  page-footer:
    left:
      - text: "Sckathach's post - Content that's both brilliant and terrible until observed"
    right:
      - text: "Home"
        href: "https://sckathach.github.io"
      - text: "About"
        href: "https://le-magicien-quantique.github.io"
  navbar:
    collapse-below: lg
    tools:
      - icon: github
        href: "https://github.com/sckathach"
    left:
      - text: "404 CTF"
        href: "404ctf/index.qmd"
      - text: "SSR"
        href: "mech-interp/subspace-rerouting/index.qmd"

  search:
    show-item-context: true
    type: overlay
  sidebar:
    - id: 404ctf
      title: "404ctf"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - "404ctf/index.qmd"
        - section: "Artificial Intelligence"
          contents:
            - text: "Poison [1/2]"
              href: "404ctf/artificial-intelligence/challenges/poison-1/index.ipynb"
            - text: "Poison [2/2]"
              href: "404ctf/artificial-intelligence/challenges/poison-2/index.ipynb"
            - text: "Backdoor"
              href: "404ctf/artificial-intelligence/challenges/backdoor/index.ipynb"
            - text: "Poison [3/2]"
              href: "404ctf/artificial-intelligence/challenges/poison-3/index.ipynb"
            - text: "Poison [1/2] - Solution"
              href: "404ctf/artificial-intelligence/solutions/poison-1/index.ipynb"
            - text: "Poison [2/2] - Solution"
              href: "404ctf/artificial-intelligence/solutions/poison-2/index.ipynb"
            - text: "Backdoor - Solution"
              href: "404ctf/artificial-intelligence/solutions/backdoor/index.ipynb"
            - text: "Poison [3/2] - Solution"
              href: "404ctf/artificial-intelligence/solutions/poison-3/index.ipynb"
        - section: "Quantum Challenges"
          contents:
            - text: "Introduction to rail encoding"
              href: "404ctf/quantum-challenges/challenges/introduction-to-rail-encoding/index.ipynb"
            - text: "Quantum Woman in the Middle"
              href: "404ctf/quantum-challenges/challenges/quantum-woman-in-the-middle/index.ipynb"
            - text: "Multiple Systems"
              href: "404ctf/quantum-challenges/challenges/multiple-systems/index.ipynb"
            - text: "Reverse Engineering"
              href: "404ctf/quantum-challenges/challenges/reverse-engineering/index.ipynb"
            - text: "Introduction to rail encoding - Solution"
              href: "404ctf/quantum-challenges/solutions/introduction-to-rail-encoding/index.ipynb"
            - text: "Quantum Woman in the Middle - Solution"
              href: "404ctf/quantum-challenges/solutions/quantum-woman-in-the-middle/index.ipynb"
            - text: "Multiple Systems - Solution"
              href: "404ctf/quantum-challenges/solutions/multiple-systems/index.ipynb"
            - text: "Reverse Engineering - Solution"
              href: "404ctf/quantum-challenges/solutions/reverse-engineering/index.ipynb"
