# Writing

## 2025

[**Exploring the multi-dimensional refusal subspace in reasoning models**](/blogs/exploring-the-multi-dimensional-refusal-subspace/) \
The refusal space in large reasoning models spans multiple directions. For models above $8$B parameters, this multi-dimensionality becomes essential as a single refusal vector is no longer sufficient to induce refusals or enable jailbreaks.

[**Combining TAP and DSPy to generate quick and efficient jailbreaks**](/blogs/dspy-tap/) \
Black-box attacks based on attacker LLMs remain highly effective against open-source models. This is an opportunity for interpretability research, as we often requires large collections of adversarial examples for experimentation.

[**404 CTF - 2025 Edition (French)**](/404ctf/2025) \
Challenges et solutions de l'édition 2025. 

[**Subspace Rerouting: Using Mechanistic Interpretability to Craft Adversarial Attacks against Large Language Models**](/blogs/subspace-rerouting/post/) \
Post following my first paper. See also the [**project webpage**](/blogs/subspace-rerouting/) for the experiements.

## 2024 

[**Exploring the use of Mechanistic Interpretability to Craft Adversarial Attacks**](/blogs/exploring-adversarial-mi/) \
My first attempt at applying interpretability methods in a practical setting. I tried to improve the Greedy Coordinate Gradient (GCG) attack using the refusal direction identified by @arditi_refusal_2024.

[**404 CTF - 2024 Edition**](/404ctf/2024) \
Challenges I created, along with their solutions. 
